name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        
  lint:
          name: Lint code with ESLint
          runs-on: ubuntu-latest
          needs: test
          steps:
            - name: Checkout code
              uses: actions/checkout@v3
      
            - name: Install dependencies
              run: npm install
      
            - name: Run ESLint
              run: npx eslint . --ext .js

              
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test  #Espera que el job "test" pase
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: csazo2408/api-k8s-demo:latest

  deploy:
            runs-on: self-hosted  #  Aquí está la clave
            needs: build-and-push
            steps:
              - name: Checkout code
                uses: actions/checkout@v3
        
              - name: Aplicar manifiestos en Minikube
                run: |
                  kubectl apply -f k8/namespace.yml
                  kubectl apply -f k8/rbac.yml
                  kubectl apply -f k8/deployment.yml
                  kubectl apply -f k8/service.yml